### ISSUE TITLE
Bitcoin Wallet

### ISSUE THREAD

**Issue by maydiamc** [Fermat-ORG/beta-testing-program#46]
#### Nombre pantalla
 
-----

##### Home

- [x] Pantalla de Transacciones recibidas (Es la de la derecha)
- [x] Pantalla de Transacciones enviadas (Es la de la izquierda)
- [x] Balance (es la circunferencia con la cantidad de bitcoin)
- [] Pop up de bienvenida
- [] Pop up de ayuda

##### Reporte de error: 

   *En la pantalla principal se observa la barra superior del movil y no permite la visibilidad de los iconos superiores de menu, send bitcoins y ayuda 
![screenshot_2016-03-01-11-08-22](https://cloud.githubusercontent.com/assets/17274154/13432060/3e700442-df9e-11e5-9f9d-f567b9ebf8f0.png)
------
##### Reporte de error: 

   No se hace sencillo encontrar la opcion de personalizacion del perfil, ademas al ingresar a la pantalla "Identity Manager" no existe una opcion para volver al menu "home", luego de darle click al boton "save changes" hay que retroceder con el boton "atras" del telefono y esto lleva al menu principal de la aplicacion Fermat y no al menu "Home" de la aplicacion Bitcoins Wallet

  
------
##### Contactos/ Fermat User

- [x] Pantalla de add Fermat user

##### Reporte de error: 

   *Al darle click al icono inferior derecho, este nos lleva a una pantalla llamada "Cripto wallet user"
![screenshot_2016-03-01-10-51-49](https://cloud.githubusercontent.com/assets/17274154/13432204/da718956-df9e-11e5-8584-85957d8943bc.png)

Al darle click al icono de la lupa que se encuentra en la parte superior y querer ingresar el nombre de cualquier contacto la aplicacion muestra un error en la pantalla y al darle click al boton de atras del telefono, la aplicacion vuelve al menu principal de Fermat y no a la aplicacion Bitcoins Wallet
![screenshot_2016-03-01-10-34-00](https://cloud.githubusercontent.com/assets/17274154/13432232/ed6fe994-df9e-11e5-833b-75835af9972a.png)

------
##### Settings

- [x] Pantalla de principal
- [] Pantalla de envio
- [] Pantalla de recibiento

##### Reporte de error: 

   *En la pantalla principal del menu setting, las letras de "enabled notifications" y "select network· son de color muy claro y no tienen buena visibilidad, ademas al momento de activar o desactivar las "enabled notifications" la aplicacion se reinicia y al ingresar de nuevo sucede lo mismo una y otra vez 
![screenshot_2016-03-01-11-18-57](https://cloud.githubusercontent.com/assets/17274154/13432395/91f08cf8-df9f-11e5-84db-f7d9f35e0d26.png)

   
------

**Comment by augusto-ponce** [comment]
@furszy @acostarodrigo

**Comment by nattyco** [comment]
@maydiamc error en search de intra user community corregido.
Pantalla de Settings se le agrego un fondo para que se puedan leer mas claramente las opciones.

**Comment by maydiamc** [comment]
#### Pantalla de Settings

* Error solucionado: buena visibilidad en las letras de la pantalla Settings 
* Nuevo error: al activar las notificaciones, regreso al menu Home y vuevo a abrir la pantalla Settings y las notificaciones aparecen desactivadas, es necesario que se coloque un boton con la opcion "save changes" para que se mantengan los cambios realizados, ademas en el momento que active las notificaciones, y volvi al NavigattionView me aparecion el icono de notificacion en la barra superior y aparecio un error que me llevo a salirme de la aplicacion por completo, ya que no me permitia abrir ninguna pantalla, luego de reiniciar la aplicacion esto dejo de ocurrir, y ya no sucedia ningun cambio al activar las notificaciones.
![screenshot_2016-03-02-13-35-42](https://cloud.githubusercontent.com/assets/17274154/13496985/46721102-e125-11e5-9146-2ccbb9f6bfed.png)

******Todos los demas errores y observaciones detallados en el issues, aún deben ser corregidos.

**Comment by maydiamc** [comment]
en la nueva actualizacion persiste el error de las notificaciones que se desactivan al salir de la pantalla settings
Modelo del telefono: Samsung Galaxy Mini S4
Numero de Version: Android 4.4.2 Kit Kat

**Comment by maydiamc** [comment]
***Erro de Contactos/Fermat User fue solucionado en la nueva actualizacion

****La sugerencia del NavigationView no fue tomada

*****Error de la barra superior del menu HOME persiste y no deja buena visibilidad de los iconos superiores.

Modelo del telefono: Samsung Galaxy Mini S4
Numero de Version: Android 4.4.2 Kit Kat
